spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  targetRevision: main
  repo: https://github.com/csun-cpointe/test-403
  helm:
    valueFiles:
      - values.yaml
      - values-dev.yaml