########################################
## CONFIG | Kafka Configs
########################################
aissemble-kafka-chart:
  kafka:
    resources:
      limits:
        memory: 2G
    autoCreateTopicsEnable: false # Enable auto creation of topics
