apiVersion: v1
kind: ConfigMap
metadata:
  name: metastore-service-config
  labels:
    aissemble-configuration-store: enabled
data:
  {{- with .Values.configMap.metastoreServiceConfig }}
  metastore-site.xml:
    {{- toYaml . | nindent 8 }}
  {{- end }}
