apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: pipeline-invocation-service
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: {{ .Values.spec.destination.namespace }}
    server: {{ .Values.spec.destination.server }}
  project: default
  source:
    path: test-403-deploy/src/main/resources/apps/pipeline-invocation-service
    repoURL: {{ .Values.spec.repo }}
    targetRevision: {{ .Values.spec.targetRevision }}
  {{- with .Values.spec.syncPolicy }}
  syncPolicy:
    {{- toYaml . | nindent 4 }}
  {{- end }}