########################################
## CONFIG | Policy Decision Point Configs Development Overrides
## See aiSSEMBLE aissemble-policy-decision-point-chart: README for more details.
## https://github.com/boozallen/aissemble/
########################################
aissemble-policy-decision-point-chart:
  image:
    imagePullPolicy: IfNotPresent
    dockerRepo: ""
  service:
    spec:
      type: LoadBalancer
      apiVersion: v1cd-2
      spec:
        ports:
          - name: rest-api
            port: 8080
            targetPort: 8080
        selector:
          app.kubernetes.io/instance: policy-decision-point
          app.kubernetes.io/name: policy-decision-point
